# Generated by Django 3.1.2 on 2020-10-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comp',
            new_name='complete',
        ),
    ]
